### ISSUE TITLE
Request to add license exception for tables

### ISSUE THREAD

**Issue by black-sliver** [black-sliver/SoEScriptDumper#9]
@CleanCodeX asked for tables (addresses, values and their names) to be released with an explicit license exception (MIT-like or BSD-like).

we need @neagix's OK for that

**Comment by neagix** [comment]
No problem for me, my contribution is really small. I give the OK. :ok: 

As for my opinion, I disagree with converting any GPL project (or making exceptions) to non-GPL :)

**Comment by black-sliver** [comment]
See #10
